-- Creator profile expansion
alter table public.profiles
  add column if not exists bio text,
  add column if not exists tiktok_handle text,
  add column if not exists instagram_handle text,
  add column if not exists youtube_handle text,
  add column if not exists tiktok_followers integer,
  add column if not exists instagram_followers integer,
  add column if not exists youtube_followers integer,
  add column if not exists website text,
  add column if not exists location text,
  add column if not exists date_of_birth date,
  add column if not exists gender text,
  add column if not exists ethnicity text,
  add column if not exists primary_niche text,
  add column if not exists secondary_niches text[] default '{}',
  add column if not exists languages text[] default '{}',
  add column if not exists engagement_rate numeric(5,2),
  add column if not exists content_style text,
  add column if not exists phone text,
  add column if not exists pronouns text,
  add column if not exists rate_ugc_video text,
  add column if not exists rate_ig_reel text,
  add column if not exists rate_tiktok text,
  add column if not exists rate_youtube text,
  add column if not exists rate_ig_story text,
  add column if not exists brands_worked_with text[] default '{}',
  add column if not exists media_kit_published boolean default false;
